#! /bin/sh -f
export RASPA_DIR=${HOME}/RASPA/simulations/
export DYLD_LIBRARY_PATH=${RASPA_DIR}/lib
export LD_LIBRARY_PATH=${RASPA_DIR}/lib

# remove calculation folders
rm -rf RestartInitial                                                                                    
rm -rf CrashRestart
rm -rf Movies
rm -rf Output
rm -rf VTK
rm -rf Restart

# run initial simulation
awk '!found && /^RestartFile/ {print "#" $0; found=1; next} {print}' simulation.input > temp && mv temp simulation.input 
awk '!found && /^#CreateNumberOfMolecules/ {sub(/^#/, ""); found=1} {print}' simulation.input > temp && mv temp simulation.input    
$RASPA_DIR/bin/simulate $1 > /dev/null 2>&1

# copy restart file
cp -r Restart RestartInitial/

# delete (random) position of adsorbate created in initial simulation
sed -i '' '/^Adsorbate-atom/d' RestartInitial/System_0/*
# add desired adsorbate position to restart file
echo "Adsorbate-atom-position:  0 0 4.56 0.0 0.0" >> RestartInitial/System_0/*

# restart simulation
awk '!found && /^#RestartFile/ {sub(/^#/, ""); found=1} {print}' simulation.input > temp && mv temp simulation.input    
awk '!found && /^CreateNumberOfMolecules/ {print "#" $0; found=1; next} {print}' simulation.input > temp && mv temp simulation.input    
$RASPA_DIR/bin/simulate $1 > /dev/null 2>&1

# print energy results:
grep -m1 -A4 "Host/Adsorbate energy:" Output/System_0/*
